# Generated by Django 3.1 on 2020-12-02 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201202_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='project',
        ),
        migrations.AddField(
            model_name='student',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.project'),
            preserve_default=False,
        ),
    ]
