# Generated by Django 3.1 on 2020-12-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201202_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='project',
        ),
        migrations.AddField(
            model_name='student',
            name='project',
            field=models.ManyToManyField(null=True, to='app.Project'),
        ),
    ]
