# Generated by Django 3.1 on 2020-12-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='document',
            field=models.FileField(default=1, upload_to='doc/'),
            preserve_default=False,
        ),
    ]
