# Generated by Django 3.1 on 2020-12-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201211_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Web-Application', 'Web-Application'), ('Desktop-Application', 'Desktop-Application'), ('Console-Application', 'Console-Application')], max_length=20),
        ),
    ]
